2024-03-03 01:14:43,923 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-03-03 01:14:45,315 - __main__ - INFO - station=> Teri Gram, result => ['126', 'Teri Gram, Gurugram, India', Timestamp('2024-03-03 06:00:00')]
2024-03-03 01:14:45,315 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-03-03 06:00:00
2024-03-03 01:14:45,778 - __main__ - INFO - station=> Vikas Sadan, result => ['114', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-03-03 06:00:00')]
2024-03-03 01:14:45,778 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-03-03 06:00:00
2024-03-03 01:14:45,779 - __main__ - INFO - Calling writeData & retrain_model functions.
2024-03-03 01:14:45,786 - __main__ - INFO - df_api columns Index(['AQI'], dtype='object')
2024-03-03 01:14:45,786 - __main__ - INFO - today=> 2024-03-03 & yesterday=> 2024-03-02
2024-03-03 01:14:45,788 - __main__ - INFO - temp_daily_aqi columns Index(['Unnamed: 0', 'Date', 'AQI'], dtype='object')
2024-03-03 01:14:45,790 - __main__ - INFO - temp_daily_aqi[2024-03-02]=> Empty DataFrame
Columns: [Unnamed: 0, AQI]
Index: []
2024-03-03 01:14:45,791 - __main__ - INFO - Index => 1458, yesterday => 2024-03-02 & AQI => 97.0
2024-03-03 01:14:45,791 - __main__ - INFO - Daily AQI data has been written to data/cleaned_data/Forecasting_time_series/sector_51_daily_aqi.csv
2024-03-03 01:14:45,791 - __main__ - INFO - Index => 1458, yesterday => 2024-03-02 & AQI => 97.0
2024-03-03 01:14:45,792 - __main__ - INFO - Daily AQI data has been written to static/data/sector_51_daily_aqi.csv
2024-03-03 01:14:45,796 - __main__ - INFO - Re-training the model & train_end is 2024-02-26 00:00:00
2024-03-03 01:14:47,335 - __main__ - INFO - Retrained the model & MAPE is 42.41%
2024-03-03 01:14:47,336 - __main__ - INFO - Retrained the model & MAE is 51.543261392551486%
2024-03-03 01:14:48,650 - __main__ - INFO - Forecast=> 2024-03-03    107.843100
2024-03-04    118.525616
2024-03-05    130.318709
2024-03-06    137.132975
2024-03-07    148.523068
Freq: D, Name: predicted_mean, dtype: float64
2024-03-03 01:14:48,650 - __main__ - INFO - The forecast data has been written to data/cleaned_data/Forecasting_time_series/forecast_sector_51_daily_aqi.csv
2024-03-03 01:14:48,651 - __main__ - INFO - The forecast data has been written to static/data/forecast_sector_51_daily_aqi.csv
2024-03-03 02:06:13,795 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-03-03 02:06:15,189 - __main__ - INFO - station=> Teri Gram, result => ['99', 'Teri Gram, Gurugram, India', Timestamp('2024-03-03 07:00:00')]
2024-03-03 02:06:15,189 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-03-03 07:00:00
2024-03-03 02:06:15,650 - __main__ - INFO - station=> Vikas Sadan, result => ['132', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-03-03 07:00:00')]
2024-03-03 02:06:15,650 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-03-03 07:00:00
2024-03-03 02:14:20,399 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-03-03 02:17:00,419 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-03-03 02:33:17,957 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
