2024-04-06 01:38:46,814 - __main__ - INFO - Calling writeData & retrain_model functions.
2024-04-06 01:38:46,821 - __main__ - INFO - df_api columns Index(['AQI'], dtype='object')
2024-04-06 01:38:46,821 - __main__ - INFO - today=> 2024-04-06 & yesterday=> 2024-04-05
2024-04-06 01:38:46,823 - __main__ - INFO - temp_daily_aqi columns Index(['Unnamed: 0', 'Date', 'AQI'], dtype='object')
2024-04-06 01:38:46,825 - __main__ - INFO - temp_daily_aqi[2024-04-05]=> Empty DataFrame
Columns: [Unnamed: 0, AQI]
Index: []
2024-04-06 01:38:46,826 - __main__ - INFO - writeData function - Exception IndexError has occured for station=> data/cleaned_data/Forecasting_time_series/sector_51_daily_aqi.csv
2024-04-06 01:38:46,830 - __main__ - INFO - Re-training the model & train_end is 2024-03-27 00:00:00
2024-04-06 01:38:48,245 - __main__ - INFO - Retrained the model & MAPE is 30.78%
2024-04-06 01:38:48,245 - __main__ - INFO - Retrained the model & MAE is 70.66275908155379%
2024-04-06 01:38:49,550 - __main__ - INFO - Forecast=> 2024-04-02    276.054348
2024-04-03    270.611658
2024-04-04    266.404386
2024-04-05    266.996555
2024-04-06    273.422792
Freq: D, Name: predicted_mean, dtype: float64
2024-04-06 01:38:49,551 - __main__ - INFO - The forecast data has been written to data/cleaned_data/Forecasting_time_series/forecast_sector_51_daily_aqi.csv
2024-04-06 01:38:49,551 - __main__ - INFO - The forecast data has been written to static/data/forecast_sector_51_daily_aqi.csv
