2024-01-14 00:32:47,679 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-01-14 00:32:48,370 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['289', 'Sector-51, Gurugram, India', Timestamp('2024-01-14 05:00:00')]
2024-01-14 00:32:48,370 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-01-14 05:00:00
2024-01-14 00:32:49,056 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['289', 'Sector-51, Gurugram, India', Timestamp('2024-01-14 05:00:00')]
2024-01-14 00:32:49,056 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-01-14 05:00:00
2024-01-14 00:32:49,742 - __main__ - INFO - station=> Teri Gram, result => ['586', 'Teri Gram, Gurugram, India', Timestamp('2024-01-14 05:00:00')]
2024-01-14 00:32:49,745 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-01-14 05:00:00
2024-01-14 00:32:50,432 - __main__ - INFO - station=> Vikas Sadan, result => ['265', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-01-14 05:00:00')]
2024-01-14 00:32:50,432 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-01-14 05:00:00
