2024-02-18 01:17:50,432 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-18 01:17:53,102 - __main__ - INFO - Calling writeData & retrain_model functions.
2024-02-18 01:17:53,108 - __main__ - INFO - df_api columns Index(['AQI'], dtype='object')
2024-02-18 01:17:53,109 - __main__ - INFO - today=> 2024-02-18 & yesterday=> 2024-02-17
2024-02-18 01:17:53,111 - __main__ - INFO - temp_daily_aqi columns Index(['Unnamed: 0', 'Date', 'AQI'], dtype='object')
2024-02-18 01:17:53,113 - __main__ - INFO - temp_daily_aqi[2024-02-17]=> Empty DataFrame
Columns: [Unnamed: 0, AQI]
Index: []
2024-02-18 01:17:53,114 - __main__ - INFO - Index => 1444, yesterday => 2024-02-17 & AQI => 282.0
2024-02-18 01:17:53,114 - __main__ - INFO - Daily AQI data has been written to data/cleaned_data/Forecasting_time_series/sector_51_daily_aqi.csv
2024-02-18 01:17:53,114 - __main__ - INFO - Index => 1444, yesterday => 2024-02-17 & AQI => 282.0
2024-02-18 01:17:53,115 - __main__ - INFO - Daily AQI data has been written to static/data/sector_51_daily_aqi.csv
2024-02-18 01:17:53,119 - __main__ - INFO - Re-training the model & train_end is 2024-02-12 00:00:00
2024-02-18 01:17:54,364 - __main__ - INFO - Retrained the model & MAPE is 20.48%
2024-02-18 01:17:54,364 - __main__ - INFO - Retrained the model & MAE is 54.016808367996305%
2024-02-18 01:17:55,771 - __main__ - INFO - Forecast=> 2024-02-18    244.016140
2024-02-19    240.050057
2024-02-20    239.961070
2024-02-21    235.008150
2024-02-22    237.084553
Freq: D, Name: predicted_mean, dtype: float64
2024-02-18 01:17:55,772 - __main__ - INFO - The forecast data has been written to data/cleaned_data/Forecasting_time_series/forecast_sector_51_daily_aqi.csv
2024-02-18 01:17:55,796 - __main__ - INFO - The forecast data has been written to static/data/forecast_sector_51_daily_aqi.csv
2024-02-18 04:19:53,488 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-18 08:20:45,756 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-18 12:29:15,994 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-18 16:21:08,762 - __main__ - INFO - setData function - AQI is not an integer. Exception ValueError has occured for station=> nise gwal
2024-02-18 16:21:09,548 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['190', 'Sector-51, Gurugram, India', Timestamp('2024-02-18 21:00:00')]
2024-02-18 16:21:09,549 - __main__ - INFO - The hourly data has been written to data/cron_job_data/sector_51_cron_output.csv with Timestamp: 2024-02-18 21:00:00
2024-02-18 16:21:10,297 - __main__ - INFO - station=> Sector-51, Gurugram, result => ['190', 'Sector-51, Gurugram, India', Timestamp('2024-02-18 21:00:00')]
2024-02-18 16:21:10,297 - __main__ - INFO - The hourly data has been written to static/data/sector_51_cron_output.csv with Timestamp: 2024-02-18 21:00:00
2024-02-18 16:21:11,021 - __main__ - INFO - station=> Teri Gram, result => ['191', 'Teri Gram, Gurugram, India', Timestamp('2024-02-18 21:00:00')]
2024-02-18 16:21:11,021 - __main__ - INFO - The hourly data has been written to data/cron_job_data/teri_gram_cron_output.csv with Timestamp: 2024-02-18 21:00:00
2024-02-18 16:21:11,712 - __main__ - INFO - station=> Vikas Sadan, result => ['123', 'Vikas Sadan Gurgaon, Gurgaon, India', Timestamp('2024-02-18 21:00:00')]
2024-02-18 16:21:11,712 - __main__ - INFO - The hourly data has been written to data/cron_job_data/vikas_sadan_cron_output.csv with Timestamp: 2024-02-18 21:00:00
